### ISSUE TITLE
Create a hero page and  navigation bar with ability to login and logout

### ISSUE THREAD

**Issue by rKamindo** [rKamindo/property#12]
**Description**
As a user, I want to be able to be greeted by a page that briefly explains what the application is about, so I can know if the application is for me, I also want the ability to get started if I want to continue.

Additionally as user, I want to navigate to different sections of my application easily as well as the ability to log in and out, I need a navigation bar.

**Acceptance Criteria**
 - Visiting the home directory should show the hero if not authenticated
 - Visiting the home directory should show the main page of the application if authenticated
 - User should be able to login through a button on the navigation bar
 - User profile picture, name, and role should be visible in the header
 - User should be able to logout
 - There should be a tab for Properties

**Task List**
- [x] Create hero page
- [x] Create a navigation bar
- [x] Configure login and logout

**Acceptance Tests**
Given: I am an unauthenticated user.
When: I visit the homepage of the application
Then:
- I should see the hero page
- The hero page should have a the logo and a headline explaining the purpose of the application
- The hero page should have a brief description of the features
- The hero page should have a prominent "Get Started" or "Sign Up" button

Given: I am an authenticated user.
When:I visit the homepage of the application.
Then:
- I should see the main content of the application.
- I should not see the hero page content.

Given: I am on any page within the application.
When: I view the navigation bar.
Then:
- I should see a "Properties" tab.
- If authenticated: I should see my profile picture, name, and role.

Given: I am an unauthenticated user on the hero page
When: I click the "Get started" button.
Then:
- I should be redirected to a login page or see a login form.
- I should be able to enter my credentials (e.g., username/email and password).
- Upon successful login, I should be redirected to the main application page.

Given: I am an authenticated user on any page within the application.
When: I click the "Logout" button.
Then:
- I should be logged out of the application.
- I should be redirected to the homepage.
- I should see the hero page.

**Additional info**
This feature will create a welcoming page to users and allow ease of login/logout and navigation of the application.
